### ISSUE TITLE
Merge data or individual data

### ISSUE THREAD

**Issue by ysu2015** [plger/scDblFinder#39]
Hi scDbIFinder developers,
Thank you so much for such wonderful package. It run sooooo fast~~~.

I have a few questions regarding the usage of scDbiFinder. Maybe because it is roughly new, there is no tutorial to follow. 
1) I assumed the "sample" parameter could be used for batches information when we deal with multiple samples/batches data. Then what would be better, detect/remove doublets from individual data and merge for further analysis, or work on merged dataset as a whole. 

2) what is the "normal/common", doublets rate, based on experience?

Thank you.

Y

**Comment by plger** [comment]
Hi,
I'm surprised you say there's not tutorial to follow: as for all bioconductor package, there's a [vignette on it](https://bioconductor.org/packages/devel/bioc/vignettes/scDblFinder/inst/doc/scDblFinder.html), which also discusses your questions. Or do you mean something different?
1. Depending on the exact version you use, the samples are treated slightly differently. In the latest version, this depends on the `multiSampleMode` argument: by default this is `split`, which is roughly equivalent to running the samples separately. The other possibility would be 'singleModelSplitThres', which runs a single classifier, but performs doublet generation and thresholding separately. This has the added value of increasing the classifier's ability to distinguish rare doublets, and was the default before 1.5.11. However, it can be mislead when the samples are technically very different, and the gains are small (and can be obtained by providing, for instance, a clustering based on all samples), which is why I reverted to 'split' by default. I'm still working on optimizing the other multi-sample approach.
2. As is indicated in the documentation, for 10x data we expect the doublet rate to be roughly 1% per thousand of cells in a capture (e.g. 10% for 10k cells). This is also the default when not specifying it. This might be different for other platforms, though.  If you're very unsure about this, you can also try using a large uncertainty around the doublet rate, e.g. `dbr.sd=0.1`: in this case the thresholding will be based virtually only on the misclassification rate.

Pierre-Luc

**Comment by ysu2015** [comment]
Hi Pierre-Luc,

Thank you so much for your help. I somehow the link provided in the Bioconduct does not work for me. But yours works great.  Thank you.

I  am working on split-seq dataset, and have very different cell numbers across different samples. I assumed that means I should run scDblFinder on individual samples before merge them.

That is very clear. Thanks again.

Y
