### ISSUE TITLE
Dimension reduction option

### ISSUE THREAD

**Issue by bjstewart1** [plger/scDblFinder#46]
Would be useful to be able to specify a dimensionality reduction in `scDblFinder` rather than automatically defaulting to PCA.
What if you have some other latent space calculated and want to work there?
What if you have corrected your PCA space with fastMNN or harmony and want to work there?

**Comment by plger** [comment]
Since the gene centers and loadings are not in the object, the input reducedDim is not available for artificial doublets, and hence it can't be used for the actual training. It is used only for the initial clustering -- unless you input the clusters, in which case it's not used at all. This means that, for this step, you can use your custom space in the following way:
```{r}
sce$fastclusters <- fastcluster(sce, rdname="myReducedDimName")
sce <- scDblFinder(sce, clusters="fastclusters")
```
In multi-sample settings, it's anyway advisable to use global clusters and detect doublets separately (the default multiSampleMode): this is more robust to technical variation and, unless you have very few cells, the classifier wouldn't anyway gain much from the additional samples.
If you wanted to use a different space for the downstream steps (i.e. also on artificial doublets) as well, you can pass a custom function to the `processing` argument.

**Comment by bjstewart1** [comment]
Useful thanks.
I will close
