### ISSUE TITLE
Unsupported matrix format (DelayedArray)

### ISSUE THREAD

**Issue by kokitsuyuzaki** [plger/scDblFinder#5]
Hi, thanks for nice package!
I found this package does not support [DelayedArray](http://bioconductor.org/packages/release/bioc/html/DelayedArray.html),
so please think about the extension.

```r
library("TENxPBMCData")
library("scRNAseq")
library("scDblFinder")

# Dense matrix
sce <- ZeiselBrainData()
is(counts(sce))
sce <- scDblFinder(sce)

# Sparse matrix
sce2 <- BaronPancreasData('human')
is(counts(sce2))
sce2 <- scDblFinder(sce2)

# DelayedArray
sce3 <- TENxPBMCData(dataset = "pbmc3k")
is(counts(sce3))
sce3 <- scDblFinder(sce3)
# Overclustering...
# clusters
#   1   2   3   4   5   6   7   8   9  10  11
# 354 345 175 162 150 193 276 293 301 312 139
# Creating ~2700 artifical doublets...
#  cbind(...) でエラー:
#   missing 'cbind' method for DataTable class DelayedMatrix
```

**Comment by plger** [comment]
Hi,
can you confirm that it still does not work when you first load `library(Matrix)`?
Thanks,

**Comment by plger** [comment]
forget my comment; I reproduced the bug and will fix it.

**Comment by plger** [comment]
@kokitsuyuzaki the lastest push includes a number of improvements, and should fix your problem (at the moment coerces the DelayedMatrix, which is perhaps not the most efficient, but at least this is on already reduced data). Some arguments/behaviors changed slightly, so please double-check with the new documentation if you encounter problems.
I'd be grateful if you could confirm that your problem is solved.

**Comment by kokitsuyuzaki** [comment]
Thanks for the rapid response!
After the re-installation, the example code above could be finished.
