### ISSUE TITLE
Exploring Overrepresented Doublets

### ISSUE THREAD

**Issue by cohenp05** [plger/scDblFinder#52]
Hello,

First, thank you for a great package. It's been incredibly useful in analyzing our datasets. I'm very interested in the methods you've developed to look at over-represented doublets as a way to explore physically interacting cells in our data. 

I have data from multiple samples run on a single lane, which I  demultiplexed using genotype-based methods (souporcell in this case). I am using your tool to identify doublets derived from the same sample but two different cell types, so I ran `scDblfinder` with the `knownDoublets` argument set to the output from souporcell. This worked great, but now I'm trying to use the `scDblFinder.stats` within the metadata to explore overrepresented doublets to look for possible cell-cell interactions. The output however doesn't specify whether identified doublets derived from the same sample or not and if they did which sample. In other words, I can't tell if doublets were formed before or after the samples were combined and I can't tell if the doublets are present in all samples or derive just from one condition. I would like to see if a doublets from a treated sample are present in the untreated sample as well or if they are in one but not the other. I know that the `samples` argument is available, but it specifies that this is for multiple lanes/independently process samples not for multiplexed samples. Is there an argument to scDblfinder where I can provide the multiplexed sample assignment and run on the same 10X lane to do this?  

Thank you for your help!

**Comment by plger** [comment]
Hi,
knowing from which samples the doublets derived won't be possible using scDblFinder, because this is not visible in the counts. However, your demultiplexing tool should provide you best hits genotypes for each cell (I haven't used souporcell, but both vireo and demuxlet give this), which you can cross with your doublets to identify their source.
A note: in most datasets, using the `knownDoublets` argument can increase the number of homotypic doublets identified, but it actually decreases the accuracy of heterotypic doublet detection (since many known doublets are not heterotypic).

**Comment by plger** [comment]
Will close this issue unless you want to discuss further.

**Comment by cohenp05** [comment]
I think you can close it. Thank you for your help!
