### ISSUE TITLE
xcgboost install

### ISSUE THREAD

**Issue by bjstewart1** [plger/scDblFinder#54]
In R version 4.1.2 
`Error: package or namespace load failed for ‘scDblFinder’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘xgboost’`

I have tried
`devtools::install_github("plger/scDblFinder")`
```Downloading GitHub repo plger/scDblFinder@HEAD

rjson   (0.2.20 -> 0.2.21 ) [CRAN]
xgboost (NA     -> 1.5.2.1) [CRAN]
Skipping 33 packages ahead of CRAN: BiocGenerics, S4Vectors, DelayedArray, Biobase, MatrixGenerics, Rhtslib, zlibbioc, GenomeInfoDbData, XVector, BiocParallel, Rsamtools, Biostrings, SummarizedExperiment, GenomicRanges, GenomeInfoDb, IRanges, BiocNeighbors, beachmat, ScaledMatrix, sparseMatrixStats, limma, DelayedMatrixStats, SingleCellExperiment, BiocIO, GenomicAlignments, BiocSingular, scuttle, metapod, bluster, edgeR, rtracklayer, scater, scran

Installing 2 packages: rjson, xgboost

Installing packages into ‘/home/jovyan/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)

Warning message in i.p(...):
“installation of package ‘xgboost’ had non-zero exit status”
✔  checking for file ‘/tmp/RtmprOot6n/remotes3b5e71218072/plger-scDblFinder-fec63bf/DESCRIPTION’ (454ms)
─  preparing ‘scDblFinder’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘scDblFinder_1.9.5.tar.gz’
   

Installing package into ‘/home/jovyan/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)

Warning message in i.p(...):
“installation of package ‘/tmp/RtmprOot6n/file3b5e6d7b9987/scDblFinder_1.9.5.tar.gz’ had non-zero exit status”
```

and

`install.packages("xgboost")`
```Installing package into ‘/home/jovyan/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)

Warning message in install.packages("xgboost"):
“installation of package ‘xgboost’ had non-zero exit status”
```

any suggestions for ways round this short of rolling back my R version?

**Comment by PeteHaitch** [comment]
Not the issue, and so unlikely to fix your problem, but the installation instructions should probably be updated to the [official Bioconductor instructions](https://bioconductor.org/packages/release/bioc/html/scDblFinder.html): `BiocManager::install("scDblFinder")`

**Comment by plger** [comment]
Hi,
as Pete writes, you should always install using `BiocManager::install` (as is indicated in the documentation), even when installing from github, otherwise some dependencies might not be found. But this is most likely not your problem since xgboost is on cran.

`install.packages("xgboost")` (without your original typo), if it fails, should give you something else than this warning, a real error message, that might be a good starting point. Then I'd suggest you check the xgboost documentation, eventually trying to see if they release a fix; the cran version is lagging behind a bit, unfortunately this one is a bit more complicated to build from the development version but instructions are [here](https://xgboost.readthedocs.io/en/latest/build.html).
