### ISSUE TITLE
Compatibility between Seurat, matrix and scDblFinder versions

### ISSUE THREAD

**Issue by hennion** [plger/scDblFinder#94]
We're trying to use scDblFinder in a environment with Seurat 5.0.1. It requires matrix > 1.6-2 which seems to be incompatible with scDblFinder. Is it possible to upgrade scDblFinder to make it compatible with recent versions of matrix and Seurat? 

Thank you very much.

**Comment by plger** [comment]
Hi,
There is no incompatibility per say, the problem is strictly with the pre-built binaries of Matrix and some packages on which scDblFinder depends -- see [e.g. this comment](https://github.com/plger/scDblFinder/issues/91#issuecomment-1825482069) and link in it.
The solution, using the package versions or your liking, is simply to build those underlying packages locally, rather than using the pre-built binaries. You should be able to do this simply by specifying the `type="source"` argument when installing.
I think this is only the `irlba` package but I'm not entirely sure, please let me know.

**Comment by Tripfantasy** [comment]
>  I think this is only the `irlba` package but I'm not entirely sure, please let me know.

In my case it was only the irlba package. This solution works great, thank you!

**Comment by bestbakerpro** [comment]
@plger 
I also met this problem，and I rebuilt  irlba package. Now scDblFinder has worked great.
install.packages("irlba",type = "source")
Thank you！

**Comment by hennion** [comment]
It finally worked restarting from a clean environment and installing irlba from source. 
Thank you all for your help!
