### ISSUE TITLE
How can I add results to back my original file

### ISSUE THREAD

**Issue by karabicicim** [plger/scDblFinder#98]
Hi,
I would like to thank you for this great toll. I successfully find doublets. However, I am not sure how can ı add this doublet information back to my Seurat object to remove doublets. 

My code line:

```
library(scDblFinder)
sce_fibro <- as.SingleCellExperiment(fibro)
dblt <- findDoubletClusters(sce_fibro, sce_fibro$SCT_snn_res.0.1)

set.seed(3435)
sce.dbl_h <- scDblFinder(sce_fibro, clusters="SCT_snn_res.0.1")
 table(sce.dbl_h$scDblFinder.class, sce.dbl_h$SCT_snn_res.0.1)
```

and ı obtain :
                       0   1   2   3   4
  singlet 607 581 439 268  82
  doublet  17  28  21  15  18

So I would like to remove doublets from my initial fibro seurat object. I attempt to load sce.dbl_h$scDblFinder.class data to fibro but I dind't find a good approach for it.

Could anyone guide me please how should ı remove doublets after I discovered them?

Thank you!

**Comment by plger** [comment]
You're running 2 methods.

findDoubletClusters gives infos about each cluster, in case some of them are entirely composed of doublets. You can use that info to remove entire clusters if you want to.
Most often, though, doublets do not form their own clusters (because doublet so the same type are, and they're often an unequal mixture of two cell types).

scDblFinder assigns each cell the probability of being a doublet. The [documentation](https://plger.github.io/scDblFinder/articles/scDblFinder.html#can-i-use-this-in-combination-with-seurat-or-other-tools) indicate how to put that info back into a Seurat object. If you want to filter them out you can simply do:

```
fibro <- fibro[,which(sce.dbl_h$scDblFinder.class=="singlet")]
```

**Comment by karabicicim** [comment]
Dear plger,

Thank you for your kind answer. It is perfectly works for me!

Best,
